### ISSUE TITLE
If cuda version can not degrade to 10.2,how to reproduce your network?

### ISSUE THREAD

**Issue by LeopoldACC** [mit-han-lab/torchsparse#66]
My machine's GPU is RTX3090,which is based on Ampere architecture and just support 11.0 as the oldest version of cuda.So is there any way to us CPU to reproduce your work? 
The error log I tried to install on my machine is shown as below
```shell
python setup.py install
running install
running bdist_egg
running egg_info
writing torchsparse.egg-info/PKG-INFO
writing dependency_links to torchsparse.egg-info/dependency_links.txt
writing top-level names to torchsparse.egg-info/top_level.txt
/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/cpp_extension.py:339: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'torchsparse.egg-info/SOURCES.txt'
writing manifest file 'torchsparse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'torchsparse_backend' extension
gcc -pthread -B /home/gz/anaconda3/envs/pc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/include -I/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/include/TH -I/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/gz/anaconda3/envs/pc/include/python3.8 -c torchsparse/src/torchsparse_bindings_gpu.cpp -o build/temp.linux-x86_64-3.8/torchsparse/src/torchsparse_bindings_gpu.o -g -O3 -fopenmp -lgomp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=torchsparse_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from torchsparse/src/convolution/convolution_gpu.h:4,
                 from torchsparse/src/torchsparse_bindings_gpu.cpp:9:
/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录
    5 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

```
Thks!

**Comment by digital-idiot** [comment]
[Torchsparse](https://github.com/mit-han-lab/torchsparse/) compiles fine with CUDA `11.3` and Pytorch (GPU) `1.8.1`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 465.27       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0    20W /  N/A |      5MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1029      G   /usr/lib/Xorg                       4MiB |
+-----------------------------------------------------------------------------+

```

---

It seems your `LD_LIBRARY_PATH` is not set properly. I can share compiled `wheel` if you want.

**Comment by zhijian-liu** [comment]
Thank you @digital-idiot!

**Comment by Violetit** [comment]
Thank you @digital-idiot!
Could you please share the compiled wheel?

**Comment by LeopoldACC** [comment]
Thank you @digital-idiot !,could you share compiled `wheel`?Thanks a lot!!

**Comment by digital-idiot** [comment]
> Thank you @digital-idiot !,could you share compiled `wheel`?Thanks a lot!!

Here you go, compiled with Python 3.8, CUDA 11.1: [Wheel @ Google Drive](https://drive.google.com/file/d/1j2uD9toP67S2dEELpdKrcqKNv-yezZlU/view?usp=sharing)

You also need `sparsehash` to be installed.

**Comment by digital-idiot** [comment]
> By the way,What tutorial should I learn if I want to learn how to solve such problem by myself in the future?

@LeopoldACC I did not understand. Are you talking about compilation? The problem is clear from the error itself. The compiler could not find the header which is part of CUDA. That means either CUDA is not installed properly or the location of the header file is not added to the library path (collection of locations where the compiler looks for headers and libraries).

**Comment by digital-idiot** [comment]
> nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

I think your `nvcc` version is dated. In my case
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.1, V11.1.58
Build cuda_11.1.r11.1/compiler.29745058_0
```
Also my driver version is `465.27` currently. Check the details using `nvidia-smi`.

**Comment by LeopoldACC** [comment]
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2020 NVIDIA Corporation
> > Built on Tue_Sep_15_19:10:02_PDT_2020
> > Cuda compilation tools, release 11.1, V11.1.74
> > Build cuda_11.1.TC455_06.29069683_0
> 
> I think your `nvcc` version is dated. In my case
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2021 NVIDIA Corporation
> Built on Sun_Mar_21_19:15:46_PDT_2021
> Cuda compilation tools, release 11.1, V11.1.58
> Build cuda_11.1.r11.1/compiler.29745058_0
> ```
> 
> Also my driver version is `465.27` currently. Check the details using `nvidia-smi`.

The version of your cuda is 11.1.58.So what I need to do is to downgrade my cude to 11.1.58?

**Comment by digital-idiot** [comment]
What is your output of `nvidia-smi`?

**Comment by LeopoldACC** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:02:00.0  On |                  N/A |
|  0%   50C    P8    31W / 370W |    431MiB / 24265MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       914      G   /usr/lib/xorg/Xorg                265MiB |
|    0   N/A  N/A      1311      G   /usr/bin/gnome-shell               51MiB |
|    0   N/A  N/A      1512      G   ...nlogin/bin/sunloginclient        6MiB |
|    0   N/A  N/A   1872117      G   ...AAAAAAAA== --shared-files       31MiB |
|    0   N/A  N/A   2919241      G   ...AAAAAAAAA= --shared-files       72MiB |
+-----------------------------------------------------------------------------+
```

**Comment by digital-idiot** [comment]
First, can you make a symlink of your `CUDA` installation directory (in my case it is `/opt/cuda`) to `/usr/local/CUDA` and try to compile `torchsparse`?

If the above did not work, update the `NVIDIA` driver to `465.27`. Then in your `conda` environment install `CUDA 11.1` to avoid messing with distro specific systemwide `CUDA` installation then check if the installed `torchsparse` works. Otherwise setup the `CUDA` paths and 'LD_LIBRARY_PATH' properly following your distro specific wikis / forums then compile and install `torchsparse` yourself.

Following links might be helpful.

[1] https://wiki.archlinux.org/title/GPGPU#Development
[2] https://wiki.archlinux.org/title/Environment_variables

**Comment by zhijian-liu** [comment]
Thank you so much @digital-idiot!

**Comment by LeopoldACC** [comment]
> First, can you make a symlink of your `CUDA` installation directory (in my case it is `/opt/cuda`) to `/usr/local/CUDA` and try to compile `torchsparse`?
> 
> If the above did not work, update the `NVIDIA` driver to `465.27`. Then in your `conda` environment install `CUDA 11.1` to avoid messing with distro specific systemwide `CUDA` installation then check if the installed `torchsparse` works. Otherwise setup the `CUDA` paths and `LD_LIBRARY_PATH` properly following your distro specific wikis / forums then compile and install `torchsparse` yourself.
> 
> Following links might be helpful.

The first way is mean as shown below in `~/.bashrc`?
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda
```

**Comment by LeopoldACC** [comment]
> First, can you make a symlink of your `CUDA` installation directory (in my case it is `/opt/cuda`) to `/usr/local/CUDA` and try to compile `torchsparse`?
> 
> If the above did not work, update the `NVIDIA` driver to `465.27`. Then in your `conda` environment install `CUDA 11.1` to avoid messing with distro specific systemwide `CUDA` installation then check if the installed `torchsparse` works. Otherwise setup the `CUDA` paths and `LD_LIBRARY_PATH` properly following your distro specific wikis / forums then compile and install `torchsparse` yourself.
> 
> Following links might be helpful.
> 
> [1] https://wiki.archlinux.org/title/GPGPU#Development
> [2] https://wiki.archlinux.org/title/Environment_variables

 Hi @digital-idiot 
I solved it by the second way to reinstall NVIDIA-driver 465,Thanks a lot for your help!!!If possible,can I connect with you to learn how to compile by myself and solve such problem(paid is ok if you need)?

**Comment by HaFred** [comment]
> > First, can you make a symlink of your `CUDA` installation directory (in my case it is `/opt/cuda`) to `/usr/local/CUDA` and try to compile `torchsparse`?
> > If the above did not work, update the `NVIDIA` driver to `465.27`. Then in your `conda` environment install `CUDA 11.1` to avoid messing with distro specific systemwide `CUDA` installation then check if the installed `torchsparse` works. Otherwise setup the `CUDA` paths and `LD_LIBRARY_PATH` properly following your distro specific wikis / forums then compile and install `torchsparse` yourself.
> > Following links might be helpful.
> > [1] https://wiki.archlinux.org/title/GPGPU#Development
> > [2] https://wiki.archlinux.org/title/Environment_variables
> 
> Hi @digital-idiot
> I solved it by the second way to reinstall NVIDIA-driver 465,Thanks a lot for your help!!!If possible,can I connect with you to learn how to compile by myself and solve such problem(paid is ok if you need)?

Hi, I am curious do you mean how to build the torchsparse wheel particularly? How is it going now? Thank you.

**Comment by L-Reichardt** [comment]
@digital-idiot Thanks a lot. I've been trying for days to successfully compile on different CUDA versions (which always lead to a freeze and crash so no error messages), however with your .whl-file I have had success.

**Comment by zouyuanpeng** [comment]
@digital-idiot I try to build torchsparse from source as your (FORCE_CUDA=1 python setup.py bdist_wheel), it succeed, while when I use it in SPVNAS project, it encounter errors: AttributeError: module 'torchsparse.backend' has no attribute 'hash_cuda'. Do you meet similar errors when build from source codes successfully and import it in other project?

**Comment by digital-idiot** [comment]
@zouyuanpeng 
I'm **guessing** that you probably did not install [Google Sparse Hash](https://github.com/sparsehash/sparsehash) library or you have improper installation of this library. Kindly check this. It is clearly mentioned in the README as dependency with notes on how to install it.

**Comment by zouyuanpeng** [comment]
> @zouyuanpeng I'm **guessing** that you probably did not install [Google Sparse Hash](https://github.com/sparsehash/sparsehash) library or you have improper installation of this library. Kindly check this. It is clearly mentioned in the README as dependency with notes on how to install it.

I have installed libsparsehash by sudo apt-get install libsparsehash-dev
