### ISSUE TITLE
TypeError: div() in downsample.py 

### ISSUE THREAD

**Issue by seekever** [mit-han-lab/torchsparse#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

downsample.py", line 28, in spdownsample
    coords[:, :3], sample_stride, rounding_mode='trunc') * sample_stride
TypeError: div() got an unexpected keyword argument 'rounding_mode'

### Environment

```markdown
- GCC: no, I used vs2019
- NVCC:10.2, V10.2.89
- PyTorch:1.6.0
- PyTorch CUDA:10.2
- TorchSparse:1.4.0
```

**Comment by CCInc** [comment]
Hello, I put up a PR to address this issue. Please let me know if it helps. https://github.com/mit-han-lab/torchsparse/pull/126

**Comment by seekever** [comment]
> Hello, I put up a PR to address this issue. Please let me know if it helps. #126

Thanks very much, it should be a perfect solution,  although I haven't test 'div().trunc()' yet. 
I just repalce 'div' with 'floor_divide' in my local codes, it works with PyTorch1.6.0
